Mirascope/mirascope

mirascope/chat/tools.py
tests/chat/test_tools.py

Closes #60 
This inclusion was breaking the usage of tool calls for other models such as Anyscale and Together AI. Removing the erroneous `tool_call` attribute from the schema appears to have solved the issue.

fix: incorrect inclusion of `tool_call` in `OpenAITool.tool_schema`

---

mirascope/cli/commands/use.py
mirascope/cli/utils.py
tests/cli/commands/test_use.py

* Added tests for use command
* Fixed bug with missing f-string
* Updated subprocess to use ["sys.executable", "-m"]
* See https://github.com/tiangolo/typer/pull/408 but replace coverage with ruff
* Problem: VSCode debugger + VSCode Testing would fail whereas pytest cli would pass
* Adding sys.executable -m fixes VSCode debugger and VSCode Testing

added tests for use

---

docs/README.md
docs/concepts/pydantic_prompts.md
mirascope/chat/utils.py
mirascope/prompts.py
poetry.lock
pyproject.toml
tests/chat/models/test_openai_chat.py
tests/chat/models/test_openai_chat_async.py
tests/chat/parsers/test_openai_parser.py
tests/chat/parsers/test_openai_parser_async.py
tests/chat/test_utils.py
tests/conftest.py
tests/test_prompts.py

A few fixes here:
1. Fixed issue with prompt messages returning a tuple and not the openai message params
2. Fixed issue with template injection. Each parsed message is formatted after parsing so the user can't inject e.g. "\nSYSTEM:INJECT\n" into the message.
3. Fixing (1) fixes issue with users not being able to directly write the `messages` array themselves inside of the prompt. Now users can define a messages property, write the `messages` array like they would normally, and everything else should just work.
4. Fix issue with installing the package. Previously we moved certain packages to "extra" even though they are really part of the core package. This causes issues for new users trying to install the package when they try to use e.g. `OpenAIChat.create` and it fails because …

fix: prompt messages to return openai types

---

tests/chat/models/test_openai_chat.py
tests/chat/models/test_openai_chat_async.py
tests/chat/parsers/test_openai_parser.py
tests/chat/parsers/test_openai_parser_async.py
tests/conftest.py

* Fixed tests with async generators which fixes code coverage
* Fixed mock of openai create to set the return value in the correct spot
* Added fixtures
* Updated fixtures to handle more cases

added coverage for tests using async generators

---

cookbook/squad_extraction/.mirascope/versions/question/0001_question.py
cookbook/squad_extraction/.mirascope/versions/question/0002_question.py
cookbook/squad_extraction/extract_answers.py
cookbook/squad_extraction/squad_prompts/question.py
docs/concepts/llm_convenience_wrappers.md
docs/concepts/pydantic_prompts.md
docs/cookbook/squad_extraction.md
examples/function_as_tool.py
examples/log.py
examples/openai_tool.py
examples/stream_openai_tool.py
examples/stream_openai_tool_async.py
mirascope/__init__.py
mirascope/chat/models/async_openai_chat.py
mirascope/chat/models/openai_chat.py
mirascope/chat/tools.py
mirascope/chat/utils.py
mirascope/prompts.py
tests/chat/models/test_openai_chat.py
tests/chat/models/test_openai_chat_async.py
tests/chat/parsers/test_openai_parser.py
tests/chat/parsers/test_openai_parser_async.py
tests/cli/commands/test_add.py
tests/cli/commands/test_remove.py
tests/cli/commands/test_use.py
tests/conftest.py
tests/test_prompts.py

- This inclusion enables co-locating all aspects of the call to the LLM that may impact the quality of the `Prompt`.

Include `_call_params: CallParams` attribute in `Prompt`

---

mirascope/chat/models/async_openai_chat.py
mirascope/chat/models/openai_chat.py
mirascope/chat/utils.py
tests/chat/models/test_openai_chat.py
tests/chat/models/test_openai_chat_async.py

- sometimes you'll want access to the completion used to extract a base model, which you can now access through the `._completion` private attribute of the returned BaseModel. It will be of type `OpenAIChatCompletion`

fix: include completion in returned BaseModel from call to extract

---

cookbook/squad_extraction/.mirascope/versions/question/0001_question.py
cookbook/squad_extraction/.mirascope/versions/question/0002_question.py
cookbook/squad_extraction/squad_prompts/question.py
docs/concepts/llm_convenience_wrappers.md
docs/cookbook/squad_extraction.md
examples/function_as_tool.py
examples/openai_tool.py
examples/stream_openai_tool.py
examples/stream_openai_tool_async.py
mirascope/chat/models/async_openai_chat.py
mirascope/chat/models/openai_chat.py
mirascope/chat/tools.py
mirascope/chat/utils.py
mirascope/prompts.py
tests/chat/models/test_openai_chat.py
tests/chat/models/test_openai_chat_async.py
tests/chat/parsers/test_openai_parser.py
tests/chat/parsers/test_openai_parser_async.py
tests/conftest.py
tests/test_prompts.py

- Now `call_params` can be set and it won't show up as part of the construction of the prompt.
- Also imported `warnings` instead of `from warnings` as that seems to be common practice.

Enable setting `call_params` like you would for `model_config` without it appearing in the construction of the prompt.

---

docs/api/anthropic/extractors.md
docs/api/mistral/calls.md
docs/api/mistral/extractors.md
docs/api/mistral/index.md
docs/api/mistral/tools.md
docs/api/mistral/types.md
docs/api/openai/wandb.md
docs/api/wandb.md
docs/concepts/generating_content.md
docs/concepts/integrations.md
mkdocs.yml

- Fix issues with nav linking to old reference for wandb
- Add missing API reference for Anthropic tools and extractors
- Add missing API reference for Mistral

docs: include missing API reference docs

---

mirascope/anthropic/calls.py
mirascope/anthropic/extractors.py
mirascope/anthropic/types.py
mirascope/base/extractors.py
mirascope/gemini/types.py
mirascope/mistral/types.py
mirascope/openai/calls.py
mirascope/openai/types.py
pyproject.toml
tests/anthropic/conftest.py
tests/anthropic/test_types.py
tests/conftest.py
tests/gemini/conftest.py
tests/gemini/test_types.py
tests/mistral/conftest.py
tests/mistral/test_types.py
tests/openai/conftest.py
tests/openai/test_calls.py
tests/openai/test_types.py

Closes #168 
- Raise RuntimeError when stop reason isn't function calls when using `tools` and `tool` convenience functions.
- Enable using `response_format={"type": "json_object"}` when using tools and extraction.
- Update Anthropic system prompt when using extract to force it to use a tool correctly.

Fix errors and openai dict

---

mirascope/base/prompts.py
poetry.lock
pyproject.toml
tests/base/test_prompts.py

- Instead of having to write your own custom property, we will automatically handle `list` attributes by injecting each string in the list into the prompt separated by "\n"
- If the attribute is a list of non-string elements (e.g. list of list), we will inject the string output of each item when calling `str(item)` on it.

feat: enable easier injection of list attributes and properties

---

mirascope/logfire/__init__.py

Add `with_logfire` to the `__all__` array in order to expose `with_logfire` from mirascope.logfire.
The static type checker pyright does not recognize the following import statement:
```
from mirascrope.logfire import with_logfire
```
And provides the following error:
```
error: "with_logfire" is not exported from module "mirascope.logfire"
  Import from "mirascope.logfire.logfire" instead (reportPrivateImportUsage)
```
In order to match the mirascope + logfire docs, adding the method to the __all__ field should make it importable. This may be something that you would want to take on across this repo.

Expose `with_logfire` from mirascope.logfire

---

mirascope/base/extractors.py
pyproject.toml
tests/openai/test_extractors.py

- `messages` already existed, so method wouldn't get copied if set in extractor
- also needed to ensure not to overwrite the method with `BasePrompt.messages` by ensuring it's defined in the extractor

fix: issue with not properly setting messages from extractor in temp call

---

docs/concepts/writing_prompts.md
mirascope/base/prompts.py
tests/base/test_prompts.py

fix: allow non-role keywords to be parsed as part of the actual role keyword

---

mirascope/cohere/types.py
mirascope/groq/types.py
mirascope/mistral/types.py
mirascope/openai/types.py
tests/groq/conftest.py
tests/groq/test_types.py
tests/mistral/conftest.py
tests/openai/conftest.py

Closes #256 
- Noticed that we were unnecessarily preventing correct behavior if `finish_reason not in ["tool_calls", "function_call"]` even if tools were present.
- This prevented proper use of `tool_choice="required"` since it results (sometimes? always?) in `finish_reason == "stop"`
- Now instead we simply check if `finish_reason == "length"` so let the user know it failed to call the tool (if it was trying to) because it ran out of tokens.
- Made other similar changes for other providers

fix: unnecessary prevention of tool calls for finish reason

---

docs/concepts/tools_(function_calling).md
examples/tool_calls.py
mirascope/base/prompts.py
pyproject.toml

Closes #265 
- Sometimes you'll want the AI to call a tool before responding.
- This means inserting the tool back into the chat history without an additional user message.
- Previously, if the `USER:` key existed there would be a message.
- Now, if the content is `""` or `None` then it won't be included in the messages array.

fix: issue where you couldn't pass in the tool call without a follow-up user message

---

mirascope/groq/utils.py

#Added cost calculation for the llama3-8b-8192 model with input cost $0.05 per 1M tokens and output cost $0.10 per 1M tokens.
fixes issue #270

Add Support for Llama3 Models in groq_api_calculate_cost Function

---

docs/README.md

The default shell in terminal for mac is zsh. We should make formatting difference pip install in zsh explicit

Update README.md with details on pip install for zsh

---

docs/concepts/supported_llm_providers.md
mirascope/anthropic/__init__.py
mirascope/anthropic/utils.py
mirascope/openai/__init__.py
mirascope/openai/utils.py
tests/anthropic/test_utils.py
tests/openai/test_utils.py

Closes #224 
Closes #225 
- Add `bedrock_client_wrapper` to `anthropic` module for wrapping `Anthropic` and `AsyncAnthropic` to use AWS Bedrock.
- Add `azure_client_wrapper` to `openai` module for wrapping `OpenAI` and `AsyncOpenAI` to use Microsoft Azure deployments.

Support for AnthropicBedrock and AzureOpenAI

---

docs/concepts/tracking_costs_for_llm_providers.md
mirascope/base/types.py
mirascope/cohere/types.py
mirascope/langfuse/langfuse.py
mirascope/logfire/logfire.py
mirascope/openai/calls.py
mirascope/openai/types.py
mirascope/pinecone/vectorstores.py
mirascope/wandb/wandb.py
mirascope/wandb/weave.py
tests/base/test_ops_utils.py
tests/openai/conftest.py
tests/openai/test_types.py
tests/wandb/test_weave.py

Made changes as discussed on  #214. 
Now,  the user when iterating through the stream can check if cost exists like this:
```python
from mirascope.openai import OpenAICall
class BookRecommender(OpenAICall):
prompt_template = "Please recommend a {genre} book."
genre: str
stream = BookRecommender(genre="fantasy").stream()
for chunk in stream:
print(chunk.content, end="")
if chunk.cost:
print(chunk.cost)
```

feat: Track costs for streaming with OpenAI

---

docs/concepts/supported_llm_providers.md
mirascope/openai/calls.py
mirascope/openai/utils.py
pyproject.toml

fix: issue where using AzureOpenAI required OPENAI_API_KEY

---

mirascope/base/tools.py
pyproject.toml

Issue was that we were calling `model_dump` but we really should be grabbing the top level fields as the key/value pairs.

fix: tool.args issue

---

mirascope/cohere/types.py

Fixed comments of `CohereCallResponseChunk` mentioned in issue #293.

fixed comments mentioned in issue #293

---

mirascope/anthropic/types.py
mirascope/base/types.py
mirascope/cohere/types.py
mirascope/gemini/types.py
mirascope/groq/types.py
mirascope/logfire/logfire.py
mirascope/mistral/types.py
mirascope/openai/types.py
mirascope/otel/otel.py
tests/anthropic/conftest.py
tests/anthropic/test_types.py
tests/cohere/test_types.py
tests/conftest.py
tests/gemini/conftest.py
tests/gemini/test_types.py
tests/groq/conftest.py
tests/groq/test_types.py
tests/mistral/conftest.py
tests/mistral/test_types.py
tests/openai/test_types.py
tests/otel/test_otel.py

* Updated otel wrapper to use experimental LLM conventions https://opentelemetry.io/docs/specs/semconv/gen-ai/llm-spans/
* Added more properties to `BaseCallResponse` and `BaseCallResponseChunk`
* model, id, usage, input_tokens, output_tokens, finish_reasons
* Fixed set_attributes warnings
* Fixed markdown styling on Logfire
* Closes #309 
* Partially implements #218

feat: otel llm updates

---

mirascope/anthropic/calls.py
mirascope/anthropic/types.py
mirascope/base/calls.py
mirascope/base/types.py
mirascope/cohere/calls.py
mirascope/cohere/types.py
mirascope/gemini/calls.py
mirascope/gemini/types.py
mirascope/groq/calls.py
mirascope/groq/types.py
mirascope/mistral/calls.py
mirascope/mistral/types.py
mirascope/openai/calls.py
mirascope/openai/types.py

feat: add  to call response types

---

docs/concepts/chat_history.md
examples/chat_history/chat_history_streaming.py

docs: added streaming example to chat history

---

mirascope/anthropic/utils.py
tests/anthropic/test_utils.py

Fixes #321 
Added `vertex_client_wrapper` to the `anthropic.utils` to extend support for inferencing against Anthropic models hosted on GCP.

GCP Wrapper

---

mirascope/core/anthropic/call_kwargs.py
mirascope/core/anthropic/call_response.py
mirascope/core/anthropic/stream.py
mirascope/core/base/_utils/_setup_call.py
mirascope/core/base/call_kwargs.py
mirascope/core/base/call_response.py
mirascope/core/base/stream.py
mirascope/core/cohere/call_kwargs.py
mirascope/core/cohere/call_response.py
mirascope/core/cohere/stream.py
mirascope/core/gemini/call_kwargs.py
mirascope/core/gemini/call_response.py
mirascope/core/gemini/stream.py
mirascope/core/gemini/tool.py
mirascope/core/groq/call_kwargs.py
mirascope/core/groq/call_response.py
mirascope/core/groq/stream.py
mirascope/core/mistral/call_kwargs.py
mirascope/core/mistral/call_response.py
mirascope/core/mistral/stream.py
mirascope/core/openai/call_kwargs.py
mirascope/core/openai/call_response.py
mirascope/core/openai/stream.py
pyproject.toml

It was taking the actual tool type as the generic making pydantic fail on validation because it was expecting `call_kwargs` to have actual tool instances. Updating this to the correct type of the provider-specific tool schema (with which we actually call the provider's API i.e. the call kwargs) fixes this issue.

fix: issue with `BaseCallKwargs` typing

---

mirascope/core/base/tool.py
tests/core/base/test_tool.py

fix: enable additional call arguments when defining tools without a type error

---

mirascope/core/anthropic/_utils/_calculate_cost.py

Closes issue [#501](https://github.com/Mirascope/mirascope/issues/501)
Extends the anthropic cost mapping to include models from bedrock and vertex

feat: add bedrock and vertex models to Anthropic cost mapping

---

mirascope/core/base/_utils/_parse_content_template.py

This PR adds support for image uris that (A) use a `data:` scheme to directly embed the base64 encoded image data or (B) use a `file:// ` scheme to reference an image on disk.
For example in a prompt template with `{url:image}` where `url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACkAAAApCAIAAAAnApehAAABEUlEQVR4nO2W7Q2EIAyG6+UmYQV3qiMwgyPQnViBVbwfXAxiLR9CTO54fxFRH9ryFqZt2+AhvZ4CD/ZgD3Z3vZv8xVog+o61dkqpnK+m+31tWU6PEMzcn82AwzUgzNeLqK+3cy4CGwPGHJ4QgbVN2Z66roeiIsaDHd+MbW1M3RnOuXDTJVVWb7m6rISS53qsKKBdst+y4q4IFyDed2el690JnGb3AyfYdeDIYzXsOjCA1Miy2EIzaiiGLdsJsSCrshh/yz72sx5f4fhQlWcJERDxCciv1617C4uXz65QTF8rbZ+Il+/LRmfizjeJFxFo7dgpOQF8zo0p2MyIoJRi8XL+GtzXqvWv9/PBHuzB/l32B6QdbKuN3JZvAAAAAElFTkSuQmCC`

support for `data:` and `file://` image uri schemes

---

examples/learn/tools/basic_usage/cohere/official_sdk.py
mirascope/core/cohere/_types.py
mirascope/core/cohere/_utils/_get_json_output.py
mirascope/core/cohere/call_response_chunk.py
tests/core/cohere/_utils/test_get_json_output.py
tests/core/cohere/_utils/test_handle_stream.py
tests/core/cohere/test_call_response_chunk.py
tests/core/cohere/test_stream.py
uv.lock

Related Issues: https://github.com/Mirascope/mirascope/pull/614
After cohere version 5.11.0, the stream type names were changed.
the PR support old and new names.

feat: Support cohere version 5.11.0

---

docs/blog/posts/llm-evaluation.md

Remove heading format applied to regular text

blog: adjust formatting

---

mirascope/beta/openai/realtime/tool.py
mirascope/core/azure/tool.py
mirascope/core/gemini/tool.py
mirascope/core/groq/tool.py
mirascope/core/mistral/tool.py
mirascope/core/openai/tool.py
mirascope/core/vertex/tool.py
pyproject.toml
tests/core/gemini/test_tool.py
tests/core/vertex/test_tool.py
uv.lock

This pull request includes changes to improve the handling of tool calls in the `mirascope/core` package. The updates ensure that the `model_json` is properly initialized even when `tool_call.function.arguments` is empty.
**Background:**
LLMs sometimes use pass an empty string for tool call function args, which was causing an unhandled exception when deserializing the function arguments string to json with jiter.
**Solution:**
Now, we detect that `tool_call.function.arguments`  is empty and simply initialize an empty dictionary (instead of trying to deserialize an empty string).
Changes to tool call handling:
* [`mirascope/core/azure/tool.py`](diffhunk://#diff-eda7cd9a429405537fae526d49224241b435b8b5b732dfd6f120a2b282fbd29eR90-R93): Added a check to initialize `model_json` to an empty …

handle empty tool call function arguments

---

mirascope/core/gemini/tool.py

This pull request addresses issue #724 by modifying the implementation of `GeminiTool.tool_schema` to correctly incorporate possible "required" parameters for the constructed schema required by`FunctionDeclaration`.
This implementation also better aligns with other models and their respective implementations; however, it prioritizes correctness for the Gemini SDK via the [documentation](https://ai.google.dev/gemini-api/docs/function-calling).

Fix `GeminiTool` and `FileSystemToolkit`

---

docs/learn/tools.md
mirascope/tools/__init__.py
mirascope/tools/system/_file_system.py
uv.lock

Related Issue: https://github.com/Mirascope/mirascope/issues/724

docs: clarify dependency requirements for pre-made tools

---

mirascope/core/base/stream.py
tests/core/base/test_stream.py

The PR fixes the error.
```python
Traceback (most recent call last):
File "/Users/koudai/Library/Application Support/JetBrains/PyCharm2024.3/scratches/scratch_52.py", line 15, in <module>
book_stream = recommend_book("fantasy")
File "/Users/koudai/PycharmProjects/mirascope/mirascope/core/base/structured_stream.py", line 289, in inner
stream=stream_decorator(fn=fn, **stream_decorator_kwargs)(
TypeError: stream_factory.<locals>.decorator() missing 1 required positional argument: 'partial_tools'
```
```python
from mirascope.core import openai, prompt_template
from pydantic import BaseModel
class Book(BaseModel):
title: str
author: str
@openai.call("gpt-4o-mini", stream=True, response_model=Book)
def recommend_book(genre: str) -> str:
return f"Recommend a {genre} book"
book_stream = …
```

fix: fix stream with response_model

---

docs/blog/posts/prompt-chaining.md
docs/learn/calls.md
examples/learn/calls/custom_client/decorator/azure/base_message_param.py
examples/learn/calls/custom_client/decorator/azure/messages.py
examples/learn/calls/custom_client/decorator/azure/shorthand.py
examples/learn/calls/custom_client/decorator/azure/string_template.py
uv.lock

Closes: https://github.com/Mirascope/mirascope/issues/761

docs: Add Azure endpoint configuration guidance and examples

---

mirascope/core/base/_utils/_format_template.py
mirascope/core/base/_utils/_parse_content_template.py
tests/core/base/_utils/test_parse_content_template.py
tests/core/base/_utils/test_parse_prompt_messages.py

Fixes: https://github.com/Mirascope/mirascope/issues/789

fix: Preserve leading newlines in prompt template parsing

---

.github/workflows/lint.yml
pyproject.toml

This PR modifies pyproject.toml so that pyright excludes the `.venv` directory, and modifies the lint GitHub workflow so as to run `pyright .` rather than `pyright mirascope test examples`.
Regarding the venv exclusion: The CONTRIBUTING.md docs say to invoke pyright via 
`uv run pyright .`
However, on my machine this hangs interminably (>5 mins). The issue is type checking the .venv directory. Per the [pyright docs](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#environment-options), .venv is excluded automatically *by pylance*, but apparently not by pyright, so it appears that manually excluding .venv is intended. After making this change, `uv run pyright .` finishes on my machine in about 16s.
With this change made, I updated the GitHub workflow to use `uv run …

pyright excludes .venv

---

mirascope/__init__.py
mirascope/core/__init__.py
mirascope/llm/__init__.py

This commit adds support for the following imports:
```py
from mirascope import Messages
from mirascope.core import BaseCallResponse, BaseStream
from mirascope.llm import CallResponse, Provider
```
Rationale: 
First, including Messages in the top level scope allows us to use only `from mirascope` imports for most of the example code, without needing to reference `mirascope.core`. This is particularly nice when we refactor to use `llm.call` by default (#811), so that most examples will only need a single line of imports from mirascope.
I didn't include `FromCallArgs` or `ResponseModelConfigDict`, out of conservativism since they aren't frequently used in example code, and it's breaking to remove them after they've been added. However I'm open to including them.
I added `BaseCallResponse` …

feat: expose more imports through mirascope, core, and llm

---

.gitignore
docs/WELCOME.md
docs/generate_provider_examples.py
docs/hooks.py
examples/learn/response_models/basic_usage/base_message_param.py
examples/learn/response_models/basic_usage/messages.py
examples/learn/response_models/basic_usage/shorthand.py
examples/learn/response_models/basic_usage/string_template.py
mirascope/core/__init__.py
mkdocs.yml
tests/docs/test_generate_provider_examples.py

This commit converts the get started docs to show provider-agnostic API usage (via @llm.call), while still showing the specific code usage for each provider.
In the UI, I kept showing provider-specific code, both for consistency with the "Official SDK" comparison that's already included, but also because it's a very direct way of showing off Mirascope's wide range of supported providers.
Since the code is now nearly identical for each provider, we can unify to a single implementation (using openai gpt-4o-mini by default), and then substitute in provider-specific logic at docs build time. I've added logic for doing so (`generate_provider_examples.py`), and a pre-build hook that invokes it. The substitution logic is tested, and ensures that we get a build time error if the provider …

feat: provider-agnostic Get Started docs

---

docs/find_missing_snippets.py
docs/generate_provider_examples.py
docs/hooks.py
docs/learn/tools.md
tests/docs/test_generate_provider_examples.py
tests/docs/test_missing_snippets.py

There are a lot of docs, and a lot of code snippets in those docs - over 2300. They are split between checked-in and autogenerated files, and often parameterized by provider, by API style, and others.
As a result, it's really easy to add missing imports (or break existing ones)—especially when adding a new provider. As a testament to that, there are currently 95 missing snippets. Most are related to the addition of the xai provider, but there are also broken google examples in the integrations docs.
This PR doesn't fix all of the missing snippets (it makes sense to wrap up #811 first as that will resolve many but not all missing xai snippets on its own). Instead, it adds a tool for enumerating all missing snippets, and an automated test to ensure no new missing snippets are added. I …

feat: check that all docs code snippets resolve

---

tests/docs/test_missing_snippets.py

This is a minor change to the test code for tracking missing snippets (#877) so we keep track of exactly how many missing examples there are. This has a few implications:
1. We won't inadvertently add any more missing imports in any of the grandfathered categories
2. I'll get slight satisfaction with each additional docs migration PR that makes number go down (at the cost of slightly more test maintenance)
3. It makes the test code self documenting about the scope of the issue

test: explicitly count missing docs imports

---

mirascope/llm/_call.py
mirascope/llm/_context.py
tests/llm/test_call.py
tests/llm/test_context.py
tests/llm/test_override.py

As presently implemented, the new `llm.context` api (#884) does not consistently work for async functions. Consider the following two examples:
```python
import asyncio
from mirascope import llm
@llm.call(provider="openai", model="gpt-4o-mini")
async def introspect_model() -> str:
return f"What model are you?"
async def example1():
print("example1:")
openai_response = await introspect_model()
print(openai_response.content)
with llm.context(provider="anthropic", model="claude-3-5-sonnet-latest"):
anthropic_response = await introspect_model()
print(anthropic_response.content)
async def example2():
print("example2:")
openai_response_future = introspect_model()
with llm.context(provider="anthropic", model="claude-3-5-sonnet-latest"):
anthropic_response_future = introspect_model() …
```

fix: make llm.context work for async functions

---

mirascope/llm/call_response.py
tests/llm/test_call_response.py
uv.lock

Fixes: https://github.com/Mirascope/mirascope/issues/914

fix: fix CallResponse common messages

---

.gitignore
docs/CONTRIBUTING.md
scripts/serve_docs_dev.py

Currently, doing docs development in a performant way requires modifying the `mkdocs.yml` config file by hand, which is tedious and can lead to unintended changes getting checked in. This PR adds `scripts/serve_docs_dev.py`, which generates a gitignored `mkdocs.dev.yml` file that has fast development configuration changes already made. Thus, users can just use `uv run python scripts/serve_docs_dev.py` and not need to modify the file by hand. The file is automatically cleaned up when the script is done. 
CONTRIBUTING.md has been updated accordingly.

feat: serve_docs_dev.py for fast docs development

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/tests.yml
uv.lock

We recently [bumped the version #](https://github.com/Mirascope/mirascope/commit/7591658aba56fbd518698aa83356613db59ec1d7) without updating `uv.lock`, with the result that the lockfile is out of date, and any usage of uv will tend to produce a somewhat confusing extra diff to a checked in file.
This PR adds `uv lock --check` to the CI lint workflow so build will fail if `uv.lock` is outdated. I'm intentionally committing just the workflow change first, so we can verify that CI correctly fails and with a helpful error message. Afterwards, I'll update `uv.lock`, at which point this PR will be good to merge.

feat: verify uv.lock is up-to-date in CI

---

mirascope/core/anthropic/call_response.py
mirascope/core/azure/call_response.py
mirascope/core/base/call_response.py
mirascope/core/bedrock/call_response.py
mirascope/core/cohere/call_response.py
mirascope/core/gemini/call_response.py
mirascope/core/google/call_response.py
mirascope/core/groq/call_response.py
mirascope/core/mistral/call_response.py
mirascope/core/openai/call_response.py
mirascope/core/vertex/call_response.py
mirascope/llm/call_response.py
tests/core/base/test_call_response.py
tests/llm/test_call.py
tests/llm/test_call_response.py
uv.lock

This updates the llm.CallResponse class so it accepts BaseCallResponses with BaseTools. Since the tool() and tools() methods on llm.CallResponse are implemented in terms of BaseCallResponse.common_tools() (which converts to llm.Tool), no other changes are needed to maintain llm.CallResponse's API contract.
Added tests, which fail prior to this change.
Fixes #940

fix: Tool usage with llm.call

---

mirascope/core/google/_utils/_convert_message_params.py
mirascope/core/google/_utils/_message_param_converter.py
mirascope/core/google/call_response.py
tests/core/google/_utils/test_convert_message_params.py
tests/core/google/_utils/test_message_param_converter.py

There were two issues at play; not getting the function calls properly from the Google response, and not handling the tool_call and tool_result message parts.
Notes from my first commit message:
The prior docstring references checking the 0th candidate 0th's part. However, both our google sdk example and these google docs[1] show using response.function_calls instead.
https://googleapis.github.io/python-genai/#function-calling
Should fix the [second part of #940](https://github.com/Mirascope/mirascope/issues/940#issuecomment-2807360626).
There don't seem to be integration tests of this part of the code, so I didn't add any.

Fix google tool

---

mirascope/core/google/call_response.py
mirascope/core/google/call_response_chunk.py
mirascope/core/google/stream.py
tests/core/google/test_call_response.py
tests/core/google/test_call_response_chunk.py
tests/core/google/test_stream.py

This PR adds thinking support for the Google provider, in a manner consistent to how I added it for Anthropic in #984.
Key changes:
- `GoogleCallResponse.content` now provides text content of the first non-thinking part
- `GoogleCallResponse.thinking` provides text content of the first thought part
- Refactored `GoogleCallResponse` to have a `_parts()` helper that throws ValueErrors rather than using type ignores (tested for coverage)
- `GoogleCallResponseChunk.thinking` added
- `GoogleStream` modified to reconstruct `GoogleCallResponse` with thinking
For test usage against the real APIs, consider the following two scripts:
```py
from dotenv import load_dotenv
from google.genai import types
from mirascope import Messages
from mirascope.core import google
from mirascope.core.google import …
```

Implement thinking support for Google

---

.claude/settings.local.json
package.json
typescript/package.json

Minor dev workflow improvements:
- Give claude various read-only permissions, as well as permissions to read relevant documentation. (Ironically openai blocks claude with 403, but maybe they'll change that sometime)
- Add a `bun run fix` command that auto-fixes all fixable errors in python and typescript. Probably not necessary because lint-staged does it for you, but may be nice to have.

V2 dev improvements

---

docs/content/_meta.json
docs/content/examples.mdx

Adds a single mdx document (6k tokens) with a broad ranging set of
examples all concatenated together. The idea is that this is very
helpful as a unified content blog that can be passed to LLMs to prime
them on Mirascope's API design and philosophy (as demonstrated in
practice), so that said LLMs can then be better rubber ducks for
exploring interface changes or improvements.
Works pretty well (Claude gives helpful / plausible suggestions on how
to e.g. integrate MCP with Mirascope v2 given just this context for
priming)

feat: add unified examples.mdx for LLM consumption

---

python/examples/structured_outputs/calls/async_context_stream.py
python/examples/structured_outputs/calls/async_stream.py
python/examples/structured_outputs/calls/context_stream.py
python/examples/structured_outputs/calls/stream.py
python/mirascope/llm/__init__.py
python/mirascope/llm/formatting/__init__.py
python/mirascope/llm/formatting/partial.py
python/mirascope/llm/responses/response.py
python/mirascope/llm/streams/base.py

Added `Partial[T]` type to properly type partial structured outputs in streaming responses.
- Added a new `Partial` generic type to the formatting module
- Updated type annotations in stream examples to use `llm.Partial[Book]` instead of `Book` for partial responses
- Added `Partial` to the public exports in the `__init__.py` files
- Updated the return type of the `format()` method in the base stream class to return `Partial[FormatT]` instead of `FormatT`
The Partial type is just the signature (no implementation or tests). Based on the equivalent code in v1, and copying the attribution header to the original GitHub comment.

feat: add llm.Partial for partial base models

---

python/mirascope/llm/responses/response.py
python/mirascope/llm/streams/base.py

In offline discussion, we agreed that having the singleton accessors for non-text content is a questionable affordance, users can write `.images[0]` if that's really what they want, and it is clearer that they may be skipping some. In particular `response.tool_call` encourages writing bad code that will miss parallel tool calling.
In the case of the `text` property, I updated docstring to show that it returns empty string if there is no text, and added a delimiter argument that defaults to `\n` for concatenating multiple text pieces.
Also removed cost tracking from response and stream.

refactor: cleanup response to remove singleton accessors (except text)

---

python/mirascope/llm/clients/__init__.py
python/mirascope/llm/clients/anthropic/__init__.py
python/mirascope/llm/clients/anthropic/client.py
python/mirascope/llm/clients/anthropic/message.py
python/mirascope/llm/clients/base/__init__.py
python/mirascope/llm/clients/base/client.py
python/mirascope/llm/clients/google/__init__.py
python/mirascope/llm/clients/google/client.py
python/mirascope/llm/clients/google/message.py
python/mirascope/llm/clients/openai/__init__.py
python/mirascope/llm/clients/openai/client.py
python/mirascope/llm/clients/openai/message.py
python/mirascope/llm/models/base.py
python/mirascope/llm/models/models.py

In offline discussion, we agreed that trying to support provider-specific messages creates a leaky abstraction / incomplete abstraction, especially since the Response will only have generic messages. 
Supporting provider-specific input messages also raises the unaddressed question of what we do with provider-specific output messages and potentially unsupported content.
I left the `AnthropicMessage`, `GoogleMessage` etc type aliases, as I think it'll be a nice convention to alias whatever the provider-specific message representation may be, to a consistent type alias.

refactor: clients only use generic llm.Message

---

python/tests/llm/clients/anthropic/test_anthropic_client.py

I don't think we should be snapshotting the raw responses, for a few
reasons:
1. It's not part of our API contract, and will tend to make spurious /
noisy diffs when we update dependency versions
2. It's not generally possible to make these assertions safely (in
OpenAI they include fields that can't be reconstructed using their
documented API, and that don't seem to have equality implemented
properly)
So, since we can't use this pattern cross-provider, I think we are
better to simplify and take it out.

chore: remove raw anthropic response snapshotting

---

python/mirascope/llm/clients/anthropic/_utils.py
python/mirascope/llm/clients/google/_utils.py
python/mirascope/llm/clients/openai/_utils.py
python/mirascope/llm/content/tool_call.py
python/mirascope/llm/tools/tool.py
python/tests/llm/clients/anthropic/test_anthropic_client.py
python/tests/llm/clients/google/test_google_client.py
python/tests/llm/clients/openai/cassettes/test_tool_usage.yaml
python/tests/llm/clients/openai/test_openai_client.py
python/tests/llm/responses/test_response.py
python/tests/llm/tools/test_tool_decorator.py

intention: ensure that processing a LLM response with tool calls can't
cause a validation error (even if llm provided invalid json). instead,
the validation error may occur when calling the tool, or potentially
(depending on provider) when attempting to include the malformed tool
call in a subsequent messsage to the llm.

refactor: store tool call args as string in content

---

python/mirascope/__init__.py
python/mirascope/graphs/finite_state_machine.py
python/mirascope/llm/agents/decorator.py
python/mirascope/llm/calls/_utils.py
python/mirascope/llm/calls/call_decorator.py
python/mirascope/llm/calls/context_call_decorator.py
python/mirascope/llm/clients/anthropic/_utils.py
python/mirascope/llm/clients/base/client.py
python/mirascope/llm/clients/openai/_utils.py
python/mirascope/llm/clients/openai/client.py
python/mirascope/llm/context/context.py
python/mirascope/llm/formatting/types.py
python/mirascope/llm/models/model.py
python/mirascope/llm/prompts/_utils.py
python/mirascope/llm/streams/__init__.py
python/mirascope/llm/tools/context_tool.py
python/mirascope/llm/tools/context_tool_decorator.py
python/mirascope/llm/tools/tool_decorator.py
python/mirascope/llm/types/jsonable.py
python/mirascope/llm/types/type_vars.py
python/pyproject.toml
python/tests/conftest.py
python/typechecking/stream.py

Adds the following ruff lint rules:
length-sort = true
length-sort-straight = true
combine-as-imports = true
extra-standard-library = ["typing_extensions"]

nit: tweak ruff lint rules

---

python/mirascope/llm/calls/call_decorator.py
python/mirascope/llm/models/_utils.py
python/tests/llm/calls/test_call_decorator.py

This is just a footgun since response.resume will not respect the client
passed to the call decorator. We will implement the client context
manager as the correct way to do this.
For now I left the client arg to llm.model as it does not present the same problem, however in the interest of just having one way to do things, it might be nice to unify on the client context manager as the only way to set the client.

refactor: remove client arg from call decorator

---

python/examples/sazed/sazed_async_context_structured.py
python/examples/sazed/sazed_async_stream_context_structured.py
python/examples/sazed/sazed_async_stream_structured.py
python/examples/sazed/sazed_async_stream_tools_context_structured.py
python/examples/sazed/sazed_async_stream_tools_structured.py
python/examples/sazed/sazed_async_structured.py
python/examples/sazed/sazed_async_tools_context_structured.py
python/examples/sazed/sazed_async_tools_structured.py
python/examples/sazed/sazed_context_structured.py
python/examples/sazed/sazed_stream_context_structured.py
python/examples/sazed/sazed_stream_structured.py
python/examples/sazed/sazed_stream_tools_context_structured.py
python/examples/sazed/sazed_stream_tools_structured.py
python/examples/sazed/sazed_structured.py
python/examples/sazed/sazed_tools_context_structured.py
python/examples/sazed/sazed_tools_structured.py
python/scripts/example_generator.ts

Prelude to getting rid of strict-or-tool; standard practice will be do
let the provider choose which mode to use

nit: sazed examples don't specify mode

---

python/mirascope/llm/__init__.py
python/mirascope/llm/clients/__init__.py
python/mirascope/llm/clients/anthropic/__init__.py
python/mirascope/llm/clients/anthropic/clients.py
python/mirascope/llm/clients/google/__init__.py
python/mirascope/llm/clients/google/clients.py
python/mirascope/llm/clients/openai/__init__.py
python/mirascope/llm/clients/openai/clients.py
python/mirascope/llm/clients/providers.py
python/tests/conftest.py
python/tests/llm/clients/anthropic/test_client.py
python/tests/llm/clients/google/test_client.py
python/tests/llm/clients/openai/test_client.py
python/tests/llm/models/test_model.py
python/tests/llm/responses/test_response_resume.py
python/tests/llm/responses/test_stream_response_resume.py

`llm.get_client(provider)` gets the client for that provider from the context manager, or constructs/retrieves the default client for that provider if there's nothing in context.
`llm.client(provider, api_key? base_url?)` retrieves the client matching those details from cache (if present), or constructs a new client and adds it to cache otherwise.
We now can retrieve both API key and base url from environment variables for consistency.
Client files renamed from `client.py` to `clients.py` to disambiguate from the `client` method for each provider.
As with `llm.Model` not allowing bare usage of `Model()`, you can't directly instantiate the clients, it's a type error to do so.
Removed `llm.OpenAIClient` etc from the top level namespace now that `llm.client()` or `llm.get_client()` are the …

refactor: clients use cached singletons

---

python/mirascope/llm/clients/base/client.py
python/mirascope/llm/models/model.py
python/mirascope/llm/responses/response.py
python/mirascope/llm/responses/stream_response.py

For now, none of the providers use it, but it's implemented as a
fallback on the base client that matches the behavior that used to be
locked in to the response implementations.
All existing code works as written, and we have full coverage because
test_call_with_tools e2e test already hits all the resume paths.

feat: add client resume api

---

python/mirascope/llm/calls/calls.py
python/mirascope/llm/clients/anthropic/_utils.py
python/mirascope/llm/clients/anthropic/clients.py
python/mirascope/llm/clients/base/client.py
python/mirascope/llm/clients/google/_utils.py
python/mirascope/llm/clients/google/clients.py
python/mirascope/llm/clients/openai/_utils.py
python/mirascope/llm/clients/openai/clients.py
python/mirascope/llm/models/models.py
python/mirascope/llm/responses/response.py
python/mirascope/llm/responses/stream_response.py
python/mirascope/llm/tools/__init__.py
python/tests/llm/clients/openai/test_client.py
python/tests/llm/responses/test_response.py
python/tests/llm/responses/test_stream_response.py

- Client APIs can now take either toolkit or tools
- Response constructor **must** take toolkit
- Call decorator still takes tools not toolkit
This is a non-breaking API change (calls to client can still just pass
tools). It does get a nice performance improvement because we now only
construct toolkits in two cases:
- When call decorator is invoked and creates a Call
- When user has called client with tools rather than toolkit
All other cases, we pass the toolkit by reference rather than
constructing it anew. This is good because constructing toolkit is
O(number of tools). We should still probably put a LRU cache in, but
it's much less urgent now that the library code constructs toolkits only
where truly necessary.

refactor: pass toolkits not tools

---

python/tests/e2e/snapshots/structured_output/strict_anthropic_snapshots.py
python/tests/e2e/snapshots/structured_output_with_formatting_instructions/strict_anthropic_snapshots.py
python/tests/e2e/snapshots/structured_output_with_tools/json_google_snapshots.py
python/tests/e2e/snapshots/structured_output_with_tools/strict_anthropic_snapshots.py
python/tests/e2e/snapshots/structured_output_with_tools/strict_google_snapshots.py
python/tests/utils.py

Tweak to exception snapshots so that it won't break if exceptions have
complex objects attached (necessary for next PR).

test: safer exception snapshotting

---

python/mirascope/llm/calls/decorator.py
python/mirascope/llm/clients/__init__.py
python/mirascope/llm/clients/openai_responses/__init__.py
python/mirascope/llm/clients/openai_responses/clients.py
python/mirascope/llm/clients/openai_responses/model_ids.py
python/mirascope/llm/clients/providers.py
python/mirascope/llm/models/models.py
python/tests/llm/clients/openai_responses/test_client.py
python/tests/llm/clients/test_providers.py

We add a new provider, "openai:responses" with a corresponding
`OpenAIResponsesClient`. Currently the client raises NotImplementedError
for every method, so this is just showing how it will fit into the
codebase (for now).
Currently I'm leaving the chat completions client as just "openai"
provider, so this approach privileges chat completions as the default
option and naming reflects this (`OpenAIClient` vs
`OpenAIResponsesClient`). I don't see this as the final design, more
just a starting point while the responses client gets developed. Before
launching beta we should revisit this. Added a TODO to this effect.

feat: stub out openai:responses provider
