Mirascope/mirascope

- docs/api/prompts.md
- examples/project-with-cli/mirascope/versions/my_prompt/0001_my_prompt.py
- examples/project-with-cli/mirascope/versions/my_prompt/0002_my_prompt.py
- examples/project-with-cli/mirascope/versions/my_prompt/0003_my_prompt.py
- examples/project-with-cli/prompts/my_prompt.py
- mirascope/__init__.py
- mirascope/chat/__init__.py
- mirascope/chat/models.py
- mirascope/chat/types.py
- mirascope/chat/utils.py
- mirascope/cli/utils.py
- mirascope/prompts.py
- tests/chat/test_models.py
- tests/chat/test_types.py
- tests/test_prompts.py
> refactor: remove `Mirascope` from class names and elsewhere + include OpenAI

- .github/ISSUE_TEMPLATES/bug_report.md
- .github/ISSUE_TEMPLATES/feature_request.md
Adding the following issue templates:
- Feature Request
- Bug Report
> docs: add templates for issues

- cookbook/movie_bot/mirascope.ini
- cookbook/movie_bot/mirascope/prompt_template.j2
- cookbook/movie_bot/mirascope/versions/movie_recommendation/0001_movie_recommendation.py
- cookbook/movie_bot/mirascope/versions/movie_recommendation/0002_movie_recommendation.py
- cookbook/movie_bot/mirascope/versions/movie_recommendation/0003_movie_recommendation.py
- mirascope/cli/commands.py
- mirascope/cli/generic/mirascope.ini.j2
- mirascope/cli/generic/prompt_template.j2
- mirascope/cli/schemas.py
- mirascope/cli/utils.py
Closes #35
Closes #36
Closes #37
* Fixed bug with docstring
* Fixed spacing inconsistency by adding a formatter
* Fixed saving non-existent prompts by adding error handling
> bugfix: fixed various bugs regarding mirascope cli

- mirascope/chat/models/async_openai_chat.py
- mirascope/chat/models/openai_chat.py
- Proxies require updating `base_url`, which we currently don't support, so I've added support for this to our chat client wrappers.
> Feat: Enable using `base_url` with convenience wrappers for things like proxies

- .vscode/launch.json
- tests/cli/commands/golden/simple_prompt/simple_prompt_with_changes.py
- tests/cli/commands/test_status.py
- tests/conftest.py
* Added tests for status
* Added debugger for pytest and python files
> added tests for status

- docs/README.md
> Back Merge v0.2.4 README updates into Dev

- docs/README.md
- Also fix examples with recent fix for messages
> Update README.md to make it more clear that you can write the messages array yourself if you'd prefer

- cookbook/squad_extraction/.mirascope/versions/question/0001_question.py
- cookbook/squad_extraction/.mirascope/versions/question/0002_question.py
- cookbook/squad_extraction/squad_prompts/question.py
- docs/concepts/llm_convenience_wrappers.md
- docs/cookbook/squad_extraction.md
- examples/function_as_tool.py
- examples/openai_tool.py
- examples/stream_openai_tool.py
- examples/stream_openai_tool_async.py
- mirascope/chat/openai/tools.py
- mirascope/prompts/prompt.py
- tests/conftest.py
- tests/prompts/test_prompt.py
> fix: use ClassVar instead of PromptConfig so we don't need to ignore warnings

- mirascope/chat/openai/parsers/openai_parser.py
- mirascope/chat/openai/parsers/openai_parser_async.py
- pyproject.toml
taken from stream_openai_tool.py and stream_openai_tool_async.py in examples
> feat: examples added to parser docstrings. 

- examples/chat_history.py
- examples/validator.py
> chore: added basic example for validation

- examples/function_as_tool.py
- examples/openai_tool.py
- mirascope/base/__init__.py
- mirascope/base/tools.py
- mirascope/base/types.py
- mirascope/gemini/prompt.py
- mirascope/gemini/tools.py
- mirascope/openai/prompt.py
- mirascope/openai/tools.py
- mirascope/wandb/prompt.py
- tests/base/test_tools.py
- tests/base/test_types.py
- tests/conftest.py
- tests/gemini/test_prompt.py
- tests/openai/test_prompt.py
- Added support for extracted `BaseTool` variants
- Added support for extracting base types (e.g. str, int, etc.) with `Prompt.extract(str)`
> Extract additional types

- docs/README.md
- docs/api/index.md
- docs/concepts/llm_convenience_wrappers.md
- mkdocs.yml
Note: some links are broken. I tried to use my best guess for where that content would be, but we'll just have to make sure and comb through this and make sure all the links work as we make changes to concepts pages.
> docs: update README with new edits.

- mirascope/cli/utils.py
- tests/cli/commands/golden/simple_prompt/0001_simple_prompt.py
- tests/cli/commands/golden/simple_prompt/0002_simple_prompt.py
- tests/cli/commands/golden/simple_prompt/simple_prompt.py
- tests/cli/commands/golden/simple_prompt/simple_prompt_with_changes.py
- tests/cli/commands/golden/simple_prompt_auto_tag/0001_simple_prompt_auto_tag.py
- tests/cli/commands/golden/simple_prompt_auto_tag/0002_simple_prompt_auto_tag.py
- tests/cli/commands/golden/simple_prompt_auto_tag/simple_prompt_auto_tag.py
- tests/cli/commands/test_add.py
Added updated list of Bases
Updated tests to use OpenAIPrompt
> bugfix: tags not working

- docs/api/anthropic/index.md
- docs/api/anthropic/prompt.md
- docs/api/anthropic/types.md
- mirascope/anthropic/prompt.py
- mirascope/anthropic/types.py
- mirascope/gemini/prompt.py
- mkdocs.yml
- tests/anthropic/conftest.py
- tests/anthropic/test_prompt.py
- tests/gemini/test_prompt.py
- Added `async_create`, `async_stream`, and `async_extract` for Gemini.
- Added `async_create` and `async_stream` for Anthropic.
> Feat: Async for Gemini and Anthropic

- docs/README.md
- docs/api/anthropic/tools.md
- docs/concepts/using_different_model_providers.md
- mirascope/anthropic/__init__.py
- mirascope/anthropic/calls.py
- mirascope/anthropic/extractors.py
- mirascope/anthropic/tools.py
- mirascope/anthropic/types.py
- mirascope/base/tools.py
- mirascope/base/utils.py
- mirascope/openai/extractors.py
- mirascope/openai/tools.py
- tests/anthropic/conftest.py
- tests/anthropic/test_extractors.py
- tests/anthropic/test_tools.py
- tests/anthropic/test_types.py
- tests/base/test_utils.py
- tests/gemini/test_extractors.py
- Tools (Function Calling) functionality for Anthropic Claude models.
> Release v0.5

- mirascope/anthropic/calls.py
- mirascope/anthropic/extractors.py
- mirascope/anthropic/tools.py
- mirascope/anthropic/types.py
- mirascope/base/calls.py
- mirascope/base/extractors.py
- mirascope/base/prompts.py
- mirascope/mistral/calls.py
- mirascope/openai/extractors.py
- mirascope/openai/tools.py
- tests/anthropic/conftest.py
- tests/anthropic/test_tools.py
- tests/anthropic/test_types.py
- Fixed issue with nested types like list, set, tuple, and dict
- Added support for def/ref so things like Enums and other references work
- Schema generation and parsing is all recursive, so it can theoretically handle whatever nesting structure you throw at it.
Still need to:
> Anthropic Function Calling Support Fixes

- mirascope/__init__.py
- mirascope/base/__init__.py
- mirascope/base/calls.py
- mirascope/openai/__init__.py
- mirascope/wandb.py
- pyproject.toml
- tests/conftest.py
- tests/openai/conftest.py
- tests/test_wandb.py
- Refactored WandbOpenAICall and WandbOpenAIExtractor into mixin classes instead.
- This makes them model agnostic :)
> feat: wandb support model agnostic mixin class

- mirascope/anthropic/calls.py
- mirascope/anthropic/extractors.py
- mirascope/anthropic/tools.py
- mirascope/anthropic/types.py
- poetry.lock
- pyproject.toml
- tests/anthropic/conftest.py
- tests/anthropic/test_extractors.py
- tests/anthropic/test_tools.py
- tests/anthropic/test_types.py
- XML tools are deprecated, releasing this as a fix release.
> chore: update Anthropic tools to use new beta tools

- docs/README.md
- docs/concepts/using_different_model_providers.md
- examples/openai_stream_async.py
- mirascope/__init__.py
- mirascope/groq/__init__.py
- mirascope/groq/calls.py
- mirascope/groq/extractors.py
- mirascope/groq/tools.py
- mirascope/groq/types.py
- mirascope/openai/calls.py
- poetry.lock
- pyproject.toml
- tests/groq/conftest.py
- tests/groq/test_calls.py
- tests/groq/test_extractors.py
- tests/groq/test_tools.py
- tests/groq/test_types.py
- Added `GroqCall`, `GroqExtractor`, and other related classes
- Supports Groq like all other model providers.
> Feat: Groq Support

- mirascope/anthropic/__init__.py
- mirascope/anthropic/calls.py
- mirascope/anthropic/extractors.py
- mirascope/anthropic/tool_streams.py
- mirascope/anthropic/types.py
- mirascope/base/utils.py
- tests/anthropic/conftest.py
- tests/anthropic/test_calls.py
- tests/anthropic/test_extractors.py
- tests/anthropic/test_tool_streams.py
- Added support for Anthropic tools streaming by using pretend JSON mode
- Works with streaming multiple tools.
- Add `stream` and `stream_async` support for AnthropicExtractor
> Additional tool streaming support for Anthropic

- docs/README.md
- docs/concepts/generating_content.md
- examples/generating_synthetic_user_data.py
- Update CoT -> Chaining (note: CoT is an overloaded term, original definition comes from a paper using single or few-shot chain of thought examples in a single prompt)
- Update README to point to correct updates in chaining doc updates
- Add example for generating synthetic data
> Update docs and examples

- mirascope/base/extractors.py
- tests/base/test_extractors.py
- tests/openai/test_extractors.py
> fix: properties not getting copied over to TempCall from extractor

- mirascope/__init__.py
- mirascope/anthropic/__init__.py
- mirascope/base/__init__.py
- mirascope/chroma/__init__.py
- mirascope/cohere/__init__.py
- mirascope/gemini/__init__.py
- mirascope/groq/__init__.py
- mirascope/mistral/__init__.py
- mirascope/openai/__init__.py
- mirascope/pinecone/__init__.py
- mirascope/rag/__init__.py
- mirascope/wandb/__init__.py
> bugfix: added __all__ to __init__.py to fix reportPrivateImportUsage

- mirascope/logfire/logfire.py
* Fixes logfire streaming with other providers. See https://github.com/pydantic/logfire/pull/107 for more details
> fix: updated streaming to behave like instrument_openai by logfire

- mirascope/anthropic/types.py
- tests/anthropic/conftest.py
- tests/anthropic/test_types.py
Closes #228 
@barapa for your reference with Gemini tools
> fix: anthropic json mode tools

- mirascope/openai/types.py
- tests/conftest.py
- tests/openai/test_types.py
> fix: issue with GPT returning an assistant message tool call instead of an actual tool call :(

- mirascope/anthropic/calls.py
- mirascope/base/calls.py
- mirascope/base/extractors.py
- mirascope/base/utils.py
- mirascope/cohere/calls.py
- mirascope/gemini/calls.py
- mirascope/groq/calls.py
- mirascope/langfuse/langfuse.py
- mirascope/mistral/calls.py
- mirascope/openai/calls.py
- poetry.lock
- pyproject.toml
- tests/base/test_utils.py
- tests/cohere/test_extractors.py
- tests/groq/test_extractors.py
- tests/openai/test_calls.py
- tests/openai/test_extractors.py
> fix: use tenacity when retries > 1 instead of always 

- mirascope/base/prompts.py
- tests/base/test_prompts.py
> bugfix: property in messages called 3 times

- mirascope/base/prompts.py
- pyproject.toml
- tests/base/test_prompts.py
Closes #251 
- Issue was due to a catching check for None that also caught the empty list.
> fix: fix issue with empty messages array injection

- docs/concepts/tools_(function_calling).md
- examples/tool_calls.py
- mirascope/base/prompts.py
- mirascope/gemini/calls.py
- mirascope/groq/calls.py
- mirascope/openai/calls.py
> Fix chat history for tool calls

- examples/chat_history_librarian.py
- mirascope/anthropic/types.py
- mirascope/base/types.py
- mirascope/cohere/types.py
- mirascope/gemini/types.py
- mirascope/groq/types.py
- mirascope/mistral/types.py
- mirascope/openai/types.py
- tests/anthropic/test_types.py
- tests/cohere/test_types.py
- tests/gemini/test_types.py
- tests/groq/test_types.py
- tests/mistral/test_types.py
- tests/openai/test_types.py
> Convenience for generating the assistant message parameter from the response of a call

- examples/logfire_examples/openai_call_async_with_logfire.py
- mirascope/core/anthropic/_utils/__init__.py
- mirascope/core/anthropic/_utils/convert_message_params.py
- mirascope/core/anthropic/_utils/setup_call.py
- mirascope/core/anthropic/tool.py
- mirascope/core/base/__init__.py
- mirascope/core/base/_structured_stream.py
- mirascope/core/base/_utils/__init__.py
- mirascope/core/base/_utils/parse_content_template.py
- mirascope/core/base/_utils/parse_prompt_messages.py
- mirascope/core/base/call_factory.py
- mirascope/core/base/message_param.py
- mirascope/core/cohere/_utils/__init__.py
- mirascope/core/cohere/_utils/convert_message_params.py
- mirascope/core/cohere/_utils/setup_call.py
- mirascope/core/gemini/_utils/__init__.py
- mirascope/core/gemini/_utils/convert_message_params.py
- mirascope/core/gemini/_utils/setup_call.py
- mirascope/core/groq/_utils/__init__.py
- mirascope/core/groq/_utils/convert_message_params.py
- mirascope/core/groq/_utils/setup_call.py
- mirascope/core/litellm/_utils/setup_call.py
- mirascope/core/mistral/_utils/__init__.py
- mirascope/core/mistral/_utils/convert_message_params.py
- mirascope/core/mistral/_utils/setup_call.py
- mirascope/core/openai/_utils/__init__.py
- mirascope/core/openai/_utils/convert_message_params.py
- mirascope/core/openai/_utils/setup_call.py
- poetry.lock
- pyproject.toml
Closes #242 
Added multimodal support for Anthropic, Gemini, OpenAI (and LiteLLM for providers that support it).
Cohere, Groq, and Mistral don't support multimodal (at least to my knowledge), so I've thrown errors when attempting to use multimodal prompt templating with those providers.
The multimodal prompt template parser currently handles text, image, and images (which is just a list of images). It is implemented such that it should be able to be easily extended to additional modalities such as audio, video, etc.
> Multimodal Support

- mirascope/core/gemini/_utils/_get_json_output.py
> fix: issue with gemini returning a proto object for lists when using tools

- mirascope/core/base/structured_stream.py
- mirascope/core/openai/_utils/_setup_call.py
- mkdocs.yml
- pyproject.toml
- tests/core/base/test_structured_stream.py
- tests/core/openai/_utils/test_setup_call.py
> fix: structured streaming + json mode bug (and a typo)

- docs/learn/provider_specific_features.md
- mirascope/core/__init__.py
- mirascope/core/anthropic/_utils/_convert_message_params.py
- mirascope/core/anthropic/call_params.py
- mirascope/core/anthropic/tool.py
- mirascope/core/base/__init__.py
- mirascope/core/base/_utils/_parse_content_template.py
- mirascope/core/base/message_param.py
- mirascope/core/base/tool.py
- mirascope/core/cohere/_utils/_convert_message_params.py
- mirascope/core/gemini/_utils/_convert_message_params.py
- mirascope/core/groq/_utils/_convert_message_params.py
- mirascope/core/groq/call_params.py
- mirascope/core/mistral/_utils/_convert_message_params.py
- mirascope/core/openai/_utils/_convert_message_params.py
- mirascope/core/openai/call_params.py
- mkdocs.yml
- tests/core/anthropic/_utils/test_convert_message_params.py
- tests/core/anthropic/test_tool.py
- tests/core/base/_utils/test_parse_content_template.py
- tests/core/cohere/_utils/test_convert_message_params.py
- tests/core/gemini/_utils/test_convert_message_params.py
- tests/core/groq/_utils/test_convert_message_params.py
- tests/core/mistral/_utils/test_convert_message_params.py
- tests/core/openai/_utils/test_convert_message_params.py
> feat: anthropic prompt caching

- docs/cookbook/evals/evaluating_documentation_agent.md
> fix: header in evaluating documentation agent

- examples/getting_started/notebooks/dynamic_config_and_chaining.ipynb
- examples/getting_started/notebooks/quickstart.ipynb
- examples/getting_started/notebooks/structured_outputs.ipynb
- examples/getting_started/notebooks/tools_and_agents.ipynb
now that prompt template decorator is optional for shorthand, we can clean up the notebooks
> docs: update getting started notebooks

- mirascope/integrations/_middleware_factory.py
- Context manager inside `middleware_factory` is now manually controlled so we can control when context closes for streaming
- Generators will still behave unexpectedly if theres an interruption/error. See https://logfire.pydantic.dev/docs/guides/advanced/generators/?h=async
> fix: manually control context manager

- .gitignore
- mirascope/core/base/_call_factory.py
- mirascope/core/base/_utils/_protocols.py
- pyproject.toml
- uv.lock
> Fix issue with annotated response model

- mirascope/tools/__init__.py
- mirascope/tools/base.py
- mirascope/tools/web/_duckduckgo.py
- mirascope/tools/web/_httpxs.py
- mirascope/tools/web/_parse_url_content.py
- mirascope/tools/web/_requests.py
- tests/tools/test_base.py
- tests/tools/web/test_duckduckgo.py
- tests/tools/web/test_httpx.py
- tests/tools/web/test_parse_url_content.py
- tests/tools/web/test_requests.py
- uv.lock
Reverts Mirascope/mirascope#648
> Revert "Revert "feat: Add Mirascope tools""

- .pre-commit-config.yaml
- mirascope/core/gemini/_utils/_convert_message_params.py
- mirascope/core/gemini/call_response.py
- mirascope/core/vertex/call_response.py
- pyproject.toml
- tests/core/gemini/test_call_response.py
- tests/core/vertex/test_call_response.py
- uv.lock
> fix: gemini multi-turn function calling

- mirascope/core/base/_utils/_parse_content_template.py
- mirascope/core/base/prompt.py
- tests/core/base/_utils/test_parse_content_template.py
- tests/core/base/test_prompt.py
- uv.lock
Related Issues: https://github.com/Mirascope/mirascope/issues/646
> feat: Support text format specifier

- mirascope/core/base/_extract.py
- tests/core/base/test_extract.py
Related Issues: https://github.com/Mirascope/mirascope/issues/659
> feat: Improve error handling

- docs/blog/posts/langchain-rag.md
This would be a great linking opportunity to the knowledge graph article
> blog: insert hyperlink

- docs/blog/posts/engineers-should-handle-prompting-llms.md
seems to be more space than usual
> blog: reduce amount of spacing between subheading and body text

- mirascope/core/openai/tool.py
- pyproject.toml
- uv.lock
> fix: issue with litellm tool construction

- mirascope/core/base/prompt.py
- pyproject.toml
- uv.lock
> Fix `prompt_template` dedent issue

- docs/blog/posts/advanced-prompt-engineering.md
> blog: add emphasis in intro

- mirascope/llm/llm_call.py
- pyproject.toml
- tests/llm/test_call.py
- uv.lock
> Fix llm call response model

- docs/blog/posts/llm-prompt.md
suggest linking the brand keyword instead
> blog: update lilypad anchor text

- mirascope/core/bedrock/_utils/_setup_call.py
- tests/core/bedrock/_utils/test_setup_call.py
Fixes: https://github.com/Mirascope/mirascope/issues/787
> fix: fix bedrock response_model

- mirascope/core/bedrock/_utils/_setup_call.py
- tests/core/bedrock/_utils/test_setup_call.py
Fixes: https://github.com/Mirascope/mirascope/issues/786
> fix: fix bedrock async client creation

- docs/blog/posts/how-to-make-a-chatbot.md
- mirascope/integrations/otel/__init__.py
- pyproject.toml
- tests/core/bedrock/_utils/test_setup_call.py
- uv.lock
> fix: issue with otel module importing hyperdx without suppression

- mirascope/core/base/call_response.py
- pyproject.toml
- uv.lock
> fix: issue with usage not being serializable

- docs/blog/posts/llm-frameworks.md
> blog: close parentheses

- mirascope/retries/__init__.py
- mirascope/retries/fallback.py
- tests/retries/test_fallback.py
> feat: fallback decorator

- mirascope/core/azure/_utils/_setup_call.py
- mirascope/core/azure/call_params.py
Closes: https://github.com/Mirascope/mirascope/issues/820
> Support latest azure sdk

- mirascope/core/google/_utils/_convert_message_params.py
- mirascope/core/google/_utils/_message_param_converter.py
- pyproject.toml
- tests/core/google/_utils/test_convert_message_params.py
- tests/core/google/_utils/test_message_param_converter.py
- tests/core/google/_utils/test_setup_call.py
- uv.lock
> Fix google image url upload part

- mirascope/core/google/call_response.py
small PR to add google token count to base response to get usage inside logfire
> add google token count

- mirascope/core/google/_utils/_convert_message_params.py
- tests/core/google/_utils/test_convert_message_params.py
Closes https://github.com/Mirascope/mirascope/issues/824
> Add google max payload size limit

- docs/blog/posts/langchain-structured-output.md
- examples/learn/response_models/few_shot_examples/base_message_param.py
- examples/learn/response_models/few_shot_examples/messages.py
- examples/learn/response_models/few_shot_examples/shorthand.py
- examples/learn/response_models/few_shot_examples/string_template.py
- mirascope/core/anthropic/call_response.py
- mirascope/core/azure/call_response.py
- mirascope/core/base/call_response.py
- mirascope/core/bedrock/call_response.py
- mirascope/core/cohere/call_response.py
- mirascope/core/gemini/call_response.py
- mirascope/core/google/call_response.py
- mirascope/core/groq/call_response.py
- mirascope/core/mistral/call_response.py
- mirascope/core/openai/call_response.py
- mirascope/core/vertex/call_response.py
- mirascope/llm/call_response.py
- tests/llm/test_call.py
- tests/llm/test_call_response.py
- tests/llm/test_stream.py
- uv.lock
> fix: issue with response model validation + few-shot issues

- mirascope/llm/llm_call.py
> fix: issue with llm.call async not having it's own inner async

- mirascope/core/openai/call_params.py
> fix: missing reasoning_effort call param for openai

- .pre-commit-config.yaml
- mirascope/core/base/__init__.py
- mirascope/core/base/_utils/_get_create_fn_or_async_create_fn.py
- mirascope/core/base/_utils/_protocols.py
- mirascope/core/base/call_response.py
- mirascope/core/base/tool.py
- mirascope/core/base/types.py
- mirascope/integrations/logfire/_utils.py
- mirascope/llm/_protocols.py
- mirascope/llm/call_response.py
- mirascope/llm/stream.py
- pyproject.toml
- tests/llm/test_call_response.py
- uv.lock
> fix: call response tool message param typing issue

- examples/learn/response_models/few_shot_examples/google/base_message_param.py
- examples/learn/response_models/few_shot_examples/google/messages.py
- examples/learn/response_models/few_shot_examples/google/shorthand.py
- examples/learn/response_models/few_shot_examples/google/string_template.py
- mirascope/beta/openai/realtime/tool.py
- mirascope/core/base/tool.py
- tests/core/openai/test_tool.py
> fix: incorrect exclusion of custom titles for fields in base models

- mirascope/core/litellm/_utils/_setup_call.py
> fix: mypy issue with litellm setup call

- mirascope/core/google/_utils/_calculate_cost.py
- mirascope/core/google/call_response.py
- mirascope/core/google/call_response_chunk.py
- mirascope/core/google/stream.py
- mirascope/llm/stream.py
- tests/core/google/test_stream.py
- tests/llm/test_stream.py
> Fix 839 840

- mirascope/core/base/__init__.py
- mirascope/core/base/_utils/_get_common_usage.py
- mirascope/core/base/types.py
- mirascope/llm/call_response.py
- tests/llm/test_call_response.py
- tests/llm/test_call_response_chunk.py
> fix: missing common Usage for llm module

- docs/blog/posts/llm-chaining.md
Apologies, now I see it would be good to add some bolding to this intro
> blog: add some bolding

- mirascope/experimental/graphs/__init__.py
- mirascope/experimental/graphs/finite_state_machine.py
- pyproject.toml
- uv.lock
> feat: FiniteStateMachine type-safe interface (without compilation)

- pyproject.toml
- uv.lock
> fix: missing proto-plus dep for google extra

- mirascope/core/google/_utils/_message_param_converter.py
- tests/core/google/test_call_response.py
> fix: google module common message param conversion role issue

- mirascope/core/openai/_utils/_convert_message_params.py
- pyproject.toml
- tests/core/openai/_utils/test_convert_message_params.py
- tests/core/openai/_utils/test_message_param_converter.py
- uv.lock
> Fix issue with OpenAI message conversion from `BaseMessageParam` with multiple tool calls

- mirascope/core/google/call_response_chunk.py
- pyproject.toml
- tests/core/google/test_call_response_chunk.py
- uv.lock
> Fix issue with `GoogleCallResponseChunk` content handling

- mirascope/core/google/_utils/_handle_stream.py
- pyproject.toml
- tests/core/google/_utils/test_handle_stream.py
- uv.lock
> Add support for streaming tools with Google

- mirascope/core/mistral/tool.py
- pyproject.toml
- tests/core/mistral/test_tool.py
- uv.lock
> Fix mistral empty tool

- mirascope/core/openai/call_params.py
> Add metadata support to OpenAI call parameters 

- mirascope/core/base/call_response.py
> fix: issue with  in tool outputs breaking serialization

- mirascope/core/bedrock/call_response.py
- tests/core/bedrock/test_call_response.py
> fix: issue with incorrect use of 'name' field with bedrock tools

- mirascope/core/azure/call_response_chunk.py
> fix: issue with azure streaming due to NoneType usage in chunk

- mirascope/mcp/_utils.py
- tests/mcp/test_client.py
> fix: issue with mcp tool fields with no default when not required

- mirascope/core/google/_utils/_convert_message_params.py
see https://github.com/Mirascope/mirascope/issues/994#issuecomment-2994501542
> fix upload images if payload size exeed 5MB when using vertex ai

- docs/content/learn/calls.mdx
- python/examples/calls/async.py
- python/examples/calls/call_async.py
- python/examples/calls/parallel_async.py
- python/pyproject.toml
n.b. disabling ruff rule "B905" in examples so we can use `zip` without strict
> feat: document async calls in calls.mdx

- docs/content/examples.mdx
- docs/scripts/generate_examples.py
It doesn't run automatically, but it does make the examples a lot easier to maintain. 
`uv run docs/scripts/generate_examples.py`
> feat: update script for examples.mdx

- python/mirascope/llm/agents/decorator.py
- python/mirascope/llm/calls/call_decorator.py
- python/mirascope/llm/calls/context_call_decorator.py
Will add the provider-specific overloads once we're auto generating them
> chore: comment out provider-specific overloads

- python/examples/tools/selective_handling_context.py
- python/mirascope/llm/agents/__init__.py
- python/mirascope/llm/agents/decorator.py
- python/mirascope/llm/calls/context_call_decorator.py
- python/typechecking/agent.py
- python/typechecking/call.py
- python/typechecking/context_call.py
- python/typechecking/utils.py
While preserving propagation of sync or async tool types
> feat: verify context tool DepsT matches call/agent

- python/mirascope/llm/responses/response.py
- python/tests/llm/responses/test_response.py
Nice to have for snapshot testing where we don't need to exhaustively
check the response.
> feat: implement response.pretty

- python/mirascope/llm/clients/anthropic/_utils.py
- python/mirascope/llm/clients/anthropic/client.py
- python/tests/llm/clients/anthropic/cassettes/test_tool_usage.yaml
- python/tests/llm/clients/anthropic/test_anthropic_client.py
Adds basic support, leaves out some optimizations like caching (to be
added as a follow on).
> feat: add anthropic support for non-streaming tool use

- python/mirascope/llm/content/tool_output.py
- python/mirascope/llm/tools/tool.py
- python/tests/llm/tools/test_tool_decorator.py
Needed to add Google tool support, and a general nice-to-have
> feat: track name on ToolOutputs

- python/mirascope/llm/responses/stream_response.py
- python/tests/llm/responses/test_stream_response.py
Some of the providers emit multiple Mirascope chunks per provider chunk,
this updates the StreamResponse so in that case, the provider chunk
shows up in stream_response.raw only once.
> fix: deduplicate raw chunks in stream response

- python/mirascope/llm/agents/agent.py
- python/mirascope/llm/agents/decorator.py
- python/mirascope/llm/calls/context_call_decorator.py
- python/mirascope/llm/clients/anthropic/client.py
- python/mirascope/llm/clients/base/client.py
- python/mirascope/llm/clients/google/client.py
- python/mirascope/llm/clients/openai/client.py
- python/mirascope/llm/models/llm.py
- python/mirascope/llm/tools/context_tool.py
- python/mirascope/llm/tools/context_tool_decorator.py
- python/mirascope/llm/tools/protocols.py
- python/mirascope/llm/tools/tool.py
- python/mirascope/llm/tools/tool_decorator.py
- python/mirascope/llm/tools/tool_schema.py
- python/mirascope/llm/tools/toolkit.py
- python/mirascope/llm/types/__init__.py
- python/mirascope/llm/types/type_vars.py
- python/tests/llm/tools/test_tool_schema.py
Also ToolSchema has **init** not from_function
> refactor: use AnyP, no RequiredDepsT, use ToolFns consistently

- python/pyproject.toml
- python/uv.lock
also, remove vestigal gemini dependency
> chore: bump google api version

- python/mirascope/llm/agents/decorator.py
- python/mirascope/llm/clients/__init__.py
- python/mirascope/llm/clients/openai/__init__.py
- python/mirascope/llm/clients/openai/clients.py
- python/mirascope/llm/clients/providers.py
- python/tests/conftest.py
- python/tests/llm/clients/openai/test_client.py
- python/tests/llm/clients/openai_responses/test_client.py
- python/tests/llm/clients/test_providers.py
- python/tests/llm/responses/test_response_resume.py
- python/tests/llm/responses/test_stream_response_resume.py
Note: for now I have not adjusted provider strings
> refactor: rename `OpenAIClient` -> `OpenAICompletionsClient`
